### ISSUE TITLE
MetalLB lab - Instructions don't mention how to get to IPAddressPool tab

### ISSUE THREAD

**Issue by gbengataylor** [rhpds/roadshow_ocpvirt_instructions#13]
https://github.com/rhpds/roadshow_ocpvirt_instructions/blob/summit/workshop/content/09_metallb.adoc#define-ip-addresspool
```
Define IP AddressPool
For this lab, we will use the same network where the OpenShift Cluster nodes are located (192.168.123.0/24) and for this, exercise we will reserve the IP range 192.168.123.200-192.168.123.250 to be used for load-balanced services in the OpenShift cluster.

Switch to project metallb-system

Switch the tab IPAddressPool and press Create IPAddressPool
```
There is no mention of how to get to the tab. A seasoned OpenShift user can find it via the APIExplorer but might be difficult for a workshop attendee. There should be explicit instructions to open it from the Installed Operators->MetalLBOperator->IpAddressPool

UPDATE: The problem is not just in section but throughout the .adoc. There are several places where it tries to evaluate and generate content based on the preinstall_operators flag that is set when the lab is provisioned. As a result, none of the content is generated. the fix should be to evaluate the flag correctly or update the instructions to ignore the flag and guide the attendee to either install the operator if it doesn't exist and then proceed. There are also sections at the top of the instructions that will also need to be modified if this route is taken

**Comment by gbengataylor** [comment]
see https://github.com/rhpds/roadshow_ocpvirt_instructions/blob/summit/workshop/content/10_backup_restore.adoc#review-operator as example

**Comment by dlbewley** [comment]
There's an ifdef that is causing the operator installation details to be omitted. 

https://github.com/rhpds/roadshow_ocpvirt_instructions/blob/summit/workshop/content/09_metallb.adoc?plain=1#L89

Suggested fix:
 Replace https://github.com/rhpds/roadshow_ocpvirt_instructions/blob/summit/workshop/content/09_metallb.adoc?plain=1#L111

with: Navigate to *Operators* -> *Installed Operators*. Select Project *metallb-system*

**Comment by gbengataylor** [comment]
Thanks @dlbewley  - There are several other occurrences where the preinstall_operators flag is evaluated, so this is a problem in other sections too. Updating the issue to properly describe the problem

**Comment by agonzalezrh** [comment]
solved
